

        # H2 데이터베이스 콘솔 활성화
        spring.h2.console.enabled=true
         # 콘솔 접속 경로 설정
         spring.h2.console.path=/h2-console
    
         # 데이터베이스 연결 정보
         # JDBC URL: H2 DB를 파일 모드가 아닌, 메모리 모드(DB 이름: recipe_db)로 실행
         spring.datasource.url=jdbc:h2:mem:recipe_db
         # 접속 유저 이름
        spring.datasource.username=sa
        # 접속 비밀번호 (없음)
        spring.datasource.password=
        # DB 드라이버 클래스 지정
        spring.datasource.driver-class-name=org.h2.Driver
   
        # JPA 설정
        # DDL(테이블 생성/수정/삭제) 자동 실행 옵션: create-drop (서버 시작 시 테이블 생성, 종료 시 삭제)
        spring.jpa.hibernate.ddl-auto=create-drop
        # JPA가 실행하는 SQL 쿼리를 로그에 표시
        spring.jpa.show-sql=true

